### ISSUE TITLE
[Trusty] : php7 purge affects php5.6

### ISSUE THREAD

**Issue by harshadyeola** [EasyEngine/easyengine#681]
``` ee stack purge/remove --php7``` affects sites running on `php5.6`.
Please refer  https://github.com/oerdnj/deb.sury.org/issues/273

User should not do ```ee stack purge/remove --php7``` if user has installed php7.0 packages.
Instead user can follow ``` ee site update example.com --php7=off```

Please attach the output of following command when open a new support request.

- [ ] lsb_release -a
root@example.com# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty

- [ ] ee -v
root@example.com# ee -v
EasyEngine v3.5.2
Copyright (c) 2015 rtCamp Solutions Pvt. Ltd.
- [ ] ee info
- [ ] wp --allow-root --info

**Comment by lawrencetaur** [comment]
my wp hhvm sites are down after installing php7.

what do i do?!

**Comment by harshadyeola** [comment]
@lawrencetaur 

Please create ticket on community (http://community.rtcamp.com/c/easyengine) forum  and also put error logs and detailed information for the issue.

**Comment by lawrencetaur** [comment]
just did that. now i cant find the ticket i just created. :/

**Comment by lawrencetaur** [comment]
my sites are down even without running ee stack purge/remove --php7

**Comment by lawrencetaur** [comment]
PHP binary:     /usr/bin/php7.0
PHP version:    7.0.3-10+deb.sury.org~trusty+1
php.ini used:   /etc/php/7.0/cli/php.ini
WP-CLI root dir:        phar://wp-cli.phar
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 0.22.0

**Comment by sarukuku** [comment]
I wonder if this has to do with the case I had today. Everything was running smoothly and I decided to run `sudo ee update`. It did its thing without errors but after it I noticed that one of my plain php+mysql sites (not any WP sites) gave a blank page with an error message that said `MySQL extension missing from your host's PHP installation`.

I restored to an older version of my VPS from a backup so everything's under control at the moment but I'm wondering if this issue of mine is something I should report as a new or is it already known?

**Comment by harshadyeola** [comment]
@sarukuku 
Your issue does not seems not related with this issue. As this issue occurs for the users which have PHP7 installed and they are trying to purge them. Actually this came from the incorrect PHP package build from the repo. However it is fixed by PHP repo maintainer I am closing this issue.

**Comment by sarukuku** [comment]
@harshadyeola ok, but are you aware of the issue I posted or should I open a new issue for it?

**Comment by harshadyeola** [comment]
@sarukuku 
Please create new topic on http://community.rtcamp.com/c/easyengine. 
Also please check updating to latest EasyEngine version (Maintain Backup as you did) if that fixes issue for you.

**Comment by sarukuku** [comment]
@harshadyeola ok, will do!

**Comment by sarukuku** [comment]
@harshadyeola just to let you know, the update didn't fix the issue. Haven't had time to create a new topic yet.
